from .fantozzi_cloud import RainyCloudUseCase
from .gets_angry_when_meeting_other_cats import GetsAngryWhenMeetingOtherCats
from .leaves_poop_stains import LeavesPoopStains
from .leaves_traces_while_walking import LeavesTracesWhileWalking
from .random_platform_jumper import JumpingPlatformsProvider, RandomPlatformJumper
from .sleeping_place import SleepingPlace
from .ufo_abduction import UfoAbductionUseCase
